/* ═══════════════════════════════════════════════════════════════════
   Mock do Pro Maker — construção de Licenciado PRO.
   Espelha o shape de ProBuilderRow da API real (GET_CONTROLEPRO):
     • isPro=false  → "Em construção" (checklist das 6 atividades do PRO)
     • isPro=true   → "É PRO" (diretos PRO + rollup da sub-rede)
   Consumido pelo DataList (layout standard) da tela ProMakerPage.
   ═══════════════════════════════════════════════════════════════════ */

export type ProMakerConsultor = {
  id: string;
  idconsultor: number;
  nome: string;
  graduacao: string;
  cidade: string;
  isPro: boolean;
  /** Direto do líder logado (sempre em destaque). */
  direto: boolean;
  nivel: number;
  /** PRO: nº de diretos PRO + rollup da sub-rede. */
  diretosPro: number;
  redePro: number;
  redeTotal: number;
  /** Construção: componentes do PRO (atual de cada atividade). */
  greenTelecom: number;
  livre: number;
  placa: number;
  solar: number;
  expansao: number;
  club: number;
};

/** Atividades do PRO (chave em ProMakerConsultor + rótulo + meta de cada caminho). */
export const ATIVIDADES: {
  key: keyof Pick<
    ProMakerConsultor,
    "greenTelecom" | "livre" | "placa" | "solar" | "expansao" | "club"
  >;
  label: string;
  meta: number;
}[] = [
  { key: "greenTelecom", label: "Clientes do mês (green/telecom/seguro)", meta: 5 },
  { key: "livre", label: "Conexão livre", meta: 1 },
  { key: "placa", label: "Placa", meta: 1 },
  { key: "solar", label: "Solar", meta: 1 },
  { key: "expansao", label: "Licenciados cadastrados", meta: 2 },
  { key: "club", label: "Club", meta: 1 },
];

/** Inteiro pt-BR (ex.: 1312 → "1.312"). */
export const num = (n: number) => n.toLocaleString("pt-BR");

/** Quantas atividades já foram iniciadas (atual > 0). */
export function atividadesIniciadas(c: ProMakerConsultor): number {
  return ATIVIDADES.filter((a) => (c[a.key] as number) > 0).length;
}

/** Quantas atividades já bateram a meta (concluídas). */
export function atividadesConcluidas(c: ProMakerConsultor): number {
  return ATIVIDADES.filter((a) => (c[a.key] as number) >= a.meta).length;
}

/* ── helpers de geração ────────────────────────────────────────────── */
type Constr = Pick<
  ProMakerConsultor,
  "greenTelecom" | "livre" | "placa" | "solar" | "expansao" | "club"
>;
const ZERO: Constr = {
  greenTelecom: 0,
  livre: 0,
  placa: 0,
  solar: 0,
  expansao: 0,
  club: 0,
};

/* ── dados ──────────────────────────────────────────────────────────
   28 consultores: ~17 em construção (vários estágios) + ~11 já PRO.    */
export const proMaker: ProMakerConsultor[] = [
  /* ─── Em construção ─────────────────────────────────────────────── */
  {
    id: "c-1001",
    idconsultor: 1001,
    nome: "Ana Beatriz Carvalho",
    graduacao: "Líder Green",
    cidade: "Belo Horizonte/MG",
    isPro: false,
    direto: true,
    nivel: 1,
    diretosPro: 0,
    redePro: 4,
    redeTotal: 38,
    ...ZERO,
    greenTelecom: 4,
    livre: 1,
    placa: 1,
    solar: 0,
    expansao: 2,
    club: 0,
  },
  {
    id: "c-1002",
    idconsultor: 1002,
    nome: "Carlos Eduardo Nunes",
    graduacao: "Consultor",
    cidade: "Contagem/MG",
    isPro: false,
    direto: true,
    nivel: 1,
    diretosPro: 0,
    redePro: 1,
    redeTotal: 12,
    ...ZERO,
    greenTelecom: 2,
    placa: 1,
    expansao: 1,
  },
  {
    id: "c-1003",
    idconsultor: 1003,
    nome: "Daniela Souza Lima",
    graduacao: "Consultor",
    cidade: "Betim/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 5,
    ...ZERO,
    greenTelecom: 1,
  },
  {
    id: "c-1004",
    idconsultor: 1004,
    nome: "Eduardo Tavares Pinto",
    graduacao: "Licenciado",
    cidade: "Sete Lagoas/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 2,
    ...ZERO,
    livre: 1,
    club: 1,
  },
  {
    id: "c-1005",
    idconsultor: 1005,
    nome: "Fernanda Rocha Alves",
    graduacao: "Líder Green",
    cidade: "Uberlândia/MG",
    isPro: false,
    direto: true,
    nivel: 1,
    diretosPro: 1,
    redePro: 3,
    redeTotal: 27,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 1,
  },
  {
    id: "c-1006",
    idconsultor: 1006,
    nome: "Gabriel Martins Reis",
    graduacao: "Consultor",
    cidade: "Juiz de Fora/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 0,
    redePro: 1,
    redeTotal: 9,
    ...ZERO,
    greenTelecom: 3,
    solar: 1,
  },
  {
    id: "c-1007",
    idconsultor: 1007,
    nome: "Helena Campos Dias",
    graduacao: "Licenciado",
    cidade: "Montes Claros/MG",
    isPro: false,
    direto: false,
    nivel: 3,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 1,
    ...ZERO,
    greenTelecom: 1,
    placa: 1,
  },
  {
    id: "c-1008",
    idconsultor: 1008,
    nome: "Igor Almeida Fonseca",
    graduacao: "Consultor",
    cidade: "Divinópolis/MG",
    isPro: false,
    direto: true,
    nivel: 1,
    diretosPro: 0,
    redePro: 2,
    redeTotal: 16,
    ...ZERO,
    greenTelecom: 4,
    livre: 1,
    expansao: 2,
  },
  {
    id: "c-1009",
    idconsultor: 1009,
    nome: "Juliana Ferreira Gomes",
    graduacao: "Licenciado",
    cidade: "Ipatinga/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 3,
    ...ZERO,
    greenTelecom: 2,
    solar: 1,
  },
  {
    id: "c-1010",
    idconsultor: 1010,
    nome: "Lucas Pereira Moraes",
    graduacao: "Consultor",
    cidade: "Poços de Caldas/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 1,
    redePro: 2,
    redeTotal: 14,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    expansao: 2,
  },
  {
    id: "c-1011",
    idconsultor: 1011,
    nome: "Mariana Castro Teixeira",
    graduacao: "Licenciado",
    cidade: "Governador Valadares/MG",
    isPro: false,
    direto: false,
    nivel: 3,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 0,
    ...ZERO,
    greenTelecom: 1,
  },
  {
    id: "c-1012",
    idconsultor: 1012,
    nome: "Nicolas Barbosa Cruz",
    graduacao: "Consultor",
    cidade: "Uberaba/MG",
    isPro: false,
    direto: true,
    nivel: 1,
    diretosPro: 0,
    redePro: 1,
    redeTotal: 11,
    ...ZERO,
    greenTelecom: 3,
    placa: 1,
    solar: 1,
    club: 1,
  },
  {
    id: "c-1013",
    idconsultor: 1013,
    nome: "Patrícia Mendes Lopes",
    graduacao: "Licenciado",
    cidade: "Varginha/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 4,
    ...ZERO,
    greenTelecom: 2,
    expansao: 1,
  },
  {
    id: "c-1014",
    idconsultor: 1014,
    nome: "Rafael Oliveira Santos",
    graduacao: "Consultor",
    cidade: "Patos de Minas/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 0,
    redePro: 1,
    redeTotal: 7,
    ...ZERO,
    greenTelecom: 4,
    livre: 1,
    solar: 1,
  },
  {
    id: "c-1015",
    idconsultor: 1015,
    nome: "Sofia Ribeiro Costa",
    graduacao: "Licenciado",
    cidade: "Pouso Alegre/MG",
    isPro: false,
    direto: false,
    nivel: 3,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 1,
    ...ZERO,
    club: 1,
  },
  {
    id: "c-1016",
    idconsultor: 1016,
    nome: "Thiago Azevedo Pires",
    graduacao: "Consultor",
    cidade: "Barbacena/MG",
    isPro: false,
    direto: true,
    nivel: 1,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 6,
    ...ZERO,
    greenTelecom: 2,
    placa: 1,
  },
  {
    id: "c-1017",
    idconsultor: 1017,
    nome: "Vanessa Cardoso Melo",
    graduacao: "Licenciado",
    cidade: "Lavras/MG",
    isPro: false,
    direto: false,
    nivel: 2,
    diretosPro: 0,
    redePro: 0,
    redeTotal: 2,
    ...ZERO,
    greenTelecom: 3,
    livre: 1,
    expansao: 1,
  },

  /* ─── É PRO ──────────────────────────────────────────────────────── */
  {
    id: "p-2001",
    idconsultor: 2001,
    nome: "Bruno Henrique Vasconcelos",
    graduacao: "Executivo Green",
    cidade: "Belo Horizonte/MG",
    isPro: true,
    direto: true,
    nivel: 1,
    diretosPro: 14,
    redePro: 86,
    redeTotal: 240,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2002",
    idconsultor: 2002,
    nome: "Camila Fontes Andrade",
    graduacao: "Executivo Green",
    cidade: "Nova Lima/MG",
    isPro: true,
    direto: true,
    nivel: 1,
    diretosPro: 11,
    redePro: 64,
    redeTotal: 181,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2003",
    idconsultor: 2003,
    nome: "Diego Ramos Siqueira",
    graduacao: "Líder Green",
    cidade: "Contagem/MG",
    isPro: true,
    direto: true,
    nivel: 1,
    diretosPro: 9,
    redePro: 47,
    redeTotal: 132,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2004",
    idconsultor: 2004,
    nome: "Elaine Moura Batista",
    graduacao: "Líder Green",
    cidade: "Betim/MG",
    isPro: true,
    direto: false,
    nivel: 2,
    diretosPro: 9,
    redePro: 41,
    redeTotal: 118,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2005",
    idconsultor: 2005,
    nome: "Felipe Cunha Macedo",
    graduacao: "Líder Green",
    cidade: "Uberlândia/MG",
    isPro: true,
    direto: true,
    nivel: 1,
    diretosPro: 7,
    redePro: 33,
    redeTotal: 95,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2006",
    idconsultor: 2006,
    nome: "Gisele Nogueira Prado",
    graduacao: "Consultor",
    cidade: "Juiz de Fora/MG",
    isPro: true,
    direto: false,
    nivel: 2,
    diretosPro: 6,
    redePro: 28,
    redeTotal: 74,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2007",
    idconsultor: 2007,
    nome: "Henrique Lacerda Vieira",
    graduacao: "Consultor",
    cidade: "Ipatinga/MG",
    isPro: true,
    direto: true,
    nivel: 1,
    diretosPro: 6,
    redePro: 24,
    redeTotal: 61,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2008",
    idconsultor: 2008,
    nome: "Isabela Freitas Coelho",
    graduacao: "Consultor",
    cidade: "Montes Claros/MG",
    isPro: true,
    direto: false,
    nivel: 2,
    diretosPro: 4,
    redePro: 17,
    redeTotal: 44,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2009",
    idconsultor: 2009,
    nome: "João Vitor Esteves",
    graduacao: "Consultor",
    cidade: "Divinópolis/MG",
    isPro: true,
    direto: true,
    nivel: 1,
    diretosPro: 3,
    redePro: 12,
    redeTotal: 31,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2010",
    idconsultor: 2010,
    nome: "Karina Duarte Salgado",
    graduacao: "Licenciado",
    cidade: "Sete Lagoas/MG",
    isPro: true,
    direto: false,
    nivel: 2,
    diretosPro: 3,
    redePro: 9,
    redeTotal: 22,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
  {
    id: "p-2011",
    idconsultor: 2011,
    nome: "Leandro Pacheco Brito",
    graduacao: "Licenciado",
    cidade: "Uberaba/MG",
    isPro: true,
    direto: false,
    nivel: 3,
    diretosPro: 2,
    redePro: 6,
    redeTotal: 15,
    ...ZERO,
    greenTelecom: 5,
    livre: 1,
    placa: 1,
    solar: 1,
    expansao: 2,
    club: 1,
  },
];

export const proMakerById: Record<string, ProMakerConsultor> = Object.fromEntries(
  proMaker.map((c) => [c.id, c]),
);

/** KPIs do topo (totais sobre o dataset mockado). */
export function proMakerKpis() {
  const pros = proMaker.filter((c) => c.isPro);
  const construcao = proMaker.filter((c) => !c.isPro);
  const marco = (n: number) => pros.filter((c) => c.diretosPro >= n).length;
  return {
    pros: pros.length,
    construcao: construcao.length,
    redeLicenciados: proMaker.length,
    p3: marco(3),
    p6: marco(6),
    p9: marco(9),
    p12: marco(12),
  };
}
